### ISSUE TITLE
Create a checkbox component.

### ISSUE THREAD

**Issue by akinde** [Multiplied-By-One/MBOne-Frontend#17]
![image](https://user-images.githubusercontent.com/22434569/104831760-940d8f80-5840-11eb-8b37-57cebe1f1954.png)

- Can use the material-ui checkbox to achieve a very similar effect and reach requirements for the component. Also comes with prepackaged transitions.
Resources:
https://material-ui.com/components/checkboxes/
https://material-ui.com/api/checkbox/

**Comment by tsukimi2** [comment]
@akinde I would like to try out this issue as well, since I'm doing the FormGroup component already and need a lower-level input component to test it out anyway.

**Comment by tsukimi2** [comment]
@akinde Just a quick question.  The checkbox requested in this issue looks really similar to the "Checkbox with FormControlLabel" in material-ui (https://material-ui.com/components/checkboxes/).  I would like to ask what's the additional requirements that this issue is trying to add on top of the material-ui Checkbox with FormControlLabel"? Thanks.

**Comment by tsukimi2** [comment]
@akindle Or does this issue mean just adding style (white color for label and around the checkbox) on the material-ui "Checkbox with FormControlLabel" and wrap it into our own checkbox component like BaseCheckbox? Thanks.

**Comment by ryanolee** [comment]
I think this would just be styling the existing https://material-ui.com/components/checkboxes/ component given the form label is going to be handled by #14 :+1:

**Comment by tsukimi2** [comment]
@akinde I just noticed that issue #23 seems to be dealing with creating Checkbox component also.  Is the current issue (#17) actually the same as issue #23? I've created the Checkbox component, but if these two issues are actually the same and since @saritasai seem to have completed the checkbox component in issue (#23) before me and mentioned it on discord already, I think I should refrain from uploading my code on the checkbox and perhaps close this issue?

**Comment by ryanolee** [comment]
Sounds reasonable. Sorry for missing this @tsukimi2 ! Might have mixed things up through misunderstandings or other means 😓 Closing this one in favour of #23 but will make sure everyone is aware of this in the future! cc @saritasai @tsukimi2
